name: ChatJP
version: '1.0-SNAPSHOT'
main: net.enabify.chatJP.ChatJP
api-version: '1.20'
folia-supported: true
authors: [ yamak493 ]

commands:
  tell:
    description: プライベートメッセージを送信します。
    usage: /tell プレイヤー名 メッセージ
    aliases: [w, msg]
  group:
    description: グループチャットに参加します
    usage: /group <番号>
    aliases: [g]
